### ISSUE TITLE
Cluster upgrade issue with cert manager 

### ISSUE THREAD

**Issue by simonkotwicz** [digitalocean/clusterlint#100]
Anyone using cert manager currently will get this error when upgrading their cluster:

> There are issues that will cause your pods to stop working. We recommend you fix them before upgrading this cluster.
> Validating webhook is configured in such a way that it may be problematic during upgrades.
> Mutating webhook is configured in such a way that it may be problematic during upgrades.

Should these be be marked as errors since api group rules are specified?
https://github.com/jetstack/cert-manager/blob/87989dbfe35bed99a9e031c71ad3a7d49030a8bf/deploy/charts/cert-manager/templates/webhook-mutating-webhook.yaml#L26-L28
https://github.com/jetstack/cert-manager/blob/87989dbfe35bed99a9e031c71ad3a7d49030a8bf/deploy/charts/cert-manager/templates/webhook-validating-webhook.yaml#L36-L38

**Comment by adamwg** [comment]
We recently fixed this in clusterlint (#99), but that fix hasn't made it to DOKS yet, so you will still see the false positive errors in the DO control panel. We're working on rolling that fix into the DOKS clusterlint integration right away, since it is a common source of confusion for users.

**Comment by simonkotwicz** [comment]
My bad, I should have checked recent commits. I guess this issue can be closed or wait until it has been rolled out to DOKS.

**Comment by larshp** [comment]
I have the same issue,
![image](https://user-images.githubusercontent.com/5888506/101145426-0a03c180-361a-11eb-9058-ac0a68dbc3cf.png)

**Comment by devurandom** [comment]
I also still run into this issue.

Following the advice in https://github.com/digitalocean/clusterlint/blob/master/checks.md#admission-controller-webhook-replacement and looking at https://github.com/jetstack/cert-manager/blob/v1.1.0/deploy/charts/cert-manager/templates/webhook-validating-webhook.yaml#L25-L30 I set `cert-manager.io/disable-validation: "true"` on my `cert-manager` namespace. According to https://github.com/digitalocean/clusterlint/blob/95e7d57b51966863fbff40bce6adc5004d836b1e/checks/doks/admission_controller_webhook_replacement.go#L81-L94 I would expect that clusterlint now stops complaining. But it does not.

In any case that would still leave https://github.com/jetstack/cert-manager/blob/v1.1.0/deploy/charts/cert-manager/templates/webhook-mutating-webhook.yaml which does not have have such a `namespaceSelector`.

**Comment by devurandom** [comment]
This issue appears to have been resolved. I just received an email that my cluster would be automatically updated and the error messages are gone from the "Version Upgrade" dialogue in the DigitalOcean UI.

**Comment by varshavaradarajan** [comment]
@devurandom - thanks, yes, we recently released a new version and vendored that on DOKS. That contains the fix: #99. Closing this.

**Comment by larshp** [comment]
I still have two errors left, is this as expected?

![image](https://user-images.githubusercontent.com/5888506/104416211-b1f2a000-5573-11eb-9529-f6d3b79d40d9.png)

**Comment by larshp** [comment]
the comments from https://github.com/digitalocean/clusterlint/issues/101 helped, I updated cert-manager via helm to latest, and now there are no errors

following the tutorial in https://www.digitalocean.com/community/tutorials/how-to-set-up-an-nginx-ingress-on-digitalocean-kubernetes-using-helm makes it difficult to upgrade
