### ISSUE TITLE
Provide pre-built binary releases

### ISSUE THREAD

**Issue by adamwg** [digitalocean/clusterlint#56]
We should provide binaries for releases so users don't need to build clusterlint themselves. For bonus points, it would be nice to build binaries automatically via actions or CircleCI when we tag a release.

**Comment by timoreimann** [comment]
I've been meaning to look into [GoReleaser](https://github.com/goreleaser/goreleaser) for other projects; perhaps clusterlint could be a good candidate to give it a whirl too.

**Comment by timoreimann** [comment]
Just saw #57 uses Github Actions which sounds like a great approach too.
