### ISSUE TITLE
"Verbose" output for fully_qualified_image check

### ISSUE THREAD

**Issue by ThelonKarrde** [digitalocean/clusterlint#67]
As suggestion, add verbose mode with flag.
As example:
In fully_qualified_image check, without Verbose mode: `Use fully qualified image for container 'prometheus-node-exporter'`
With Verbose mode: `Use fully qualified image for container 'prometheus-node-exporter', linted image name be docker name check: $correct_image_name`.
In script any way you call `ParseAnyReference` function, why not to share the output of this function?

**Comment by varshavaradarajan** [comment]
How about just changing the message for the fully-qualified image check to `Use fully qualified image for container 'prometheus-node-exporter', linted image name be docker name check: $correct_image_name` ? I don't see a need for a verbose mode to show a different message as its not applicable to all checks? If the message from any other check is vague, we can alter that to be more clear.

cc @adamwg

**Comment by adamwg** [comment]
A verbose mode is an interesting idea for the future - there are many checks where we could expand messages and even provide fix suggestions. But I agree, for this specific instance just adding the suggested image name to the output would be appropriate.

Slightly shorter suggested text:
```
Use fully qualified image name '%s' for container '%s'.
```
