### ISSUE TITLE
Unused Confimap Check does not consider configMapKeyRef for pod env vars

### ISSUE THREAD

**Issue by cherma22** [digitalocean/clusterlint#78]
Looking at the [function](https://github.com/digitalocean/clusterlint/blob/cb603bc39a95e8817108263d3f01dcd03c6df45b/checks/basic/unused_config_map.go#L150) that checks for env vars in a pod that correspond to a ConfigMap, this considers ConfigMapRef, but not `configMapKeyRef`. The latter per the [docs](https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/#define-a-container-environment-variable-with-data-from-a-single-configmap) is also a valid usage of a ConfigMap.

1. I am running the latest release of clusterlint to do some checking.
1. I would expect to see no warnings for unused ConfigMaps, as these are consumed with `configMapKeyRef`
1. I am getting warnings for unused ConfigMaps, that are clearly being used by `configMapKeyRef` when the yaml is reviewed.

**Comment by adamwg** [comment]
Thanks for reporting this! Agreed, this is an oversight - we should fix the check to also consider `configMapKeyRef`.
