### ISSUE TITLE
Add a check for cronjobs with a concurrencyPolicy of Allow

### ISSUE THREAD

**Issue by timoreimann** [digitalocean/clusterlint#95]
A cronjob configured with a `concurrencyPolicy` of `Allow` has the potential for overloading a cluster if a cronjob-managed pod cannot manage to finish in time. The impact we are occasionally seeing is that job-pods created from subsequent cron intervals pile up over time, sometimes leading to hundreds or thousands of pods that stay pending.

We should implement a check that triggers a warning for `Allow` cronjobs and suggests to use one of the safer alternative modes `Forbid` or `Replace`.

**Comment by jasimmons** [comment]
Hey @timoreimann, I'm going to pick this up! 😄

**Comment by varshavaradarajan** [comment]
fixed by #97
