### ISSUE TITLE
Add resource requirements check to doks group

### ISSUE THREAD

**Issue by varshavaradarajan** [digitalocean/clusterlint#96]
The resource-requirements check is in the basic group right now. However, many of doks users face resource contention issues because they may not have followed this best practice of setting resource limits on their pods. We currently run all the checks in the doks group before an upgrade. We can show this warning to users if this check is added to the doks group as well.

**Comment by fish-dango** [comment]
Hello @varshavaradarajan! I can try this out 

Any pointers for this?

**Comment by varshavaradarajan** [comment]
@fish-dango - thanks for your interest! :) The `resource-requirements` check is already added to the basic group here: https://github.com/digitalocean/clusterlint/blob/master/checks/basic/resource_requests.go#L40, you can add `doks` to the slice there.

**Comment by varshavaradarajan** [comment]
fixed via #120
